name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew test build --no-daemon

      - name: Publish with Gradle
        if: github.ref == 'refs/heads/custom/useBadGamesRepo'
        env:
          USERNAME: ${{ secrets.REPO_USER }}
          TOKEN: ${{ secrets.REPO_PASSWORD }}

        run: ./gradlew publish --no-daemon